#!/usr/bin/env python3
"""Aggregate every AgentVerse demo's agentverse.yaml into one catalog index.

Demos are fully independent: each ships its own ``agentverse.yaml`` at its root.
This script scans ``src/`` for those manifests, validates each against
``agentverse.schema.json``, and writes the aggregated catalog. Because the index
is generated, no shared file is hand-edited to add a demo.

Usage (run from ``src/`` or anywhere; paths resolve relative to this file):

    python templates/catalog/build_catalog.py --validate <path/to/agentverse.yaml>
    python templates/catalog/build_catalog.py --check      # validate all, exit 1 on failure
    python templates/catalog/build_catalog.py --write       # regenerate catalog.json + CATALOG.md

Dependencies: pyyaml, jsonschema  (pip install pyyaml jsonschema)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("Missing dependency: pyyaml. Run: pip install pyyaml jsonschema")

try:
    from jsonschema import Draft202012Validator
except ImportError:  # pragma: no cover
    sys.exit("Missing dependency: jsonschema. Run: pip install pyyaml jsonschema")

HERE = Path(__file__).resolve().parent
SCHEMA_PATH = HERE / "agentverse.schema.json"
# src/ is two levels up: src/templates/catalog/build_catalog.py
SRC_ROOT = HERE.parent.parent
MANIFEST_NAME = "agentverse.yaml"
# Folders under src/ that never contain a demo.
EXCLUDE_DIRS = {"templates"}


def load_schema() -> Draft202012Validator:
    with SCHEMA_PATH.open(encoding="utf-8") as fh:
        return Draft202012Validator(json.load(fh))


def discover_manifests() -> list[Path]:
    """Every immediate subfolder of src/ may hold one agentverse.yaml."""
    found: list[Path] = []
    for child in sorted(SRC_ROOT.iterdir()):
        if not child.is_dir() or child.name in EXCLUDE_DIRS:
            continue
        manifest = child / MANIFEST_NAME
        if manifest.exists():
            found.append(manifest)
    return found


def validate_manifest(path: Path, validator: Draft202012Validator) -> list[str]:
    """Return a list of human-readable error strings (empty == valid)."""
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        return [f"YAML parse error: {exc}"]
    if not isinstance(data, dict):
        return ["Manifest is not a mapping/object."]
    errors = sorted(validator.iter_errors(data), key=lambda e: list(e.path))
    return [f"{'/'.join(str(p) for p in e.path) or '<root>'}: {e.message}" for e in errors]


def load_manifest(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def cmd_validate(target: Path, validator: Draft202012Validator) -> int:
    errors = validate_manifest(target, validator)
    if errors:
        print(f"INVALID  {target}")
        for err in errors:
            print(f"  - {err}")
        return 1
    print(f"OK       {target}")
    return 0


def cmd_check(validator: Draft202012Validator) -> int:
    manifests = discover_manifests()
    if not manifests:
        print("No agentverse.yaml manifests found under src/.")
        return 0
    failed = 0
    for path in manifests:
        errors = validate_manifest(path, validator)
        rel = path.relative_to(SRC_ROOT)
        if errors:
            failed += 1
            print(f"INVALID  {rel}")
            for err in errors:
                print(f"  - {err}")
        else:
            print(f"OK       {rel}")
    print(f"\n{len(manifests) - failed}/{len(manifests)} manifests valid.")
    return 1 if failed else 0


def build_index(validator: Draft202012Validator) -> tuple[list[dict], int]:
    """Return (entries, failure_count). Invalid manifests are skipped."""
    entries: list[dict] = []
    failed = 0
    for path in discover_manifests():
        errors = validate_manifest(path, validator)
        rel = path.relative_to(SRC_ROOT)
        if errors:
            failed += 1
            print(f"skip (invalid): {rel}", file=sys.stderr)
            continue
        data = load_manifest(path)
        data["_path"] = str(rel.parent).replace("\\", "/")
        entries.append(data)
    entries.sort(key=lambda d: d.get("name", ""))
    return entries, failed


def render_markdown(entries: list[dict]) -> str:
    lines = [
        "# AgentVerse Catalog",
        "",
        "> Generated by `templates/catalog/build_catalog.py`. Do not edit by hand —",
        "> add or update a demo's `agentverse.yaml` and rerun the generator.",
        "",
        f"**{len(entries)} demo(s).**",
        "",
        "| Demo | Tagline | Status | Difficulty | Pattern | Agents |",
        "|------|---------|--------|------------|---------|--------|",
    ]
    for e in entries:
        path = e.get("_path", e.get("name", ""))
        title = f"[{e.get('title', e.get('name'))}]({path}/)"
        tagline = e.get("tagline", "").replace("|", "\\|")
        agents = ", ".join(a.get("name", "") for a in e.get("agents", []))
        lines.append(
            f"| {title} | {tagline} | {e.get('status', '')} | "
            f"{e.get('difficulty', '')} | {e.get('orchestration', '')} | {agents} |"
        )
    lines.append("")
    return "\n".join(lines)


def cmd_write(validator: Draft202012Validator) -> int:
    entries, failed = build_index(validator)
    catalog = {"apiVersion": "agentverse/v1", "count": len(entries), "demos": entries}
    json_path = SRC_ROOT / "catalog.json"
    md_path = SRC_ROOT / "CATALOG.md"
    json_path.write_text(json.dumps(catalog, indent=2, ensure_ascii=False), encoding="utf-8")
    md_path.write_text(render_markdown(entries), encoding="utf-8")
    print(f"Wrote {json_path.relative_to(SRC_ROOT)} and {md_path.relative_to(SRC_ROOT)} "
          f"({len(entries)} demo(s)).")
    if failed:
        print(f"Warning: {failed} invalid manifest(s) were skipped.", file=sys.stderr)
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--validate", metavar="PATH", help="Validate a single manifest file.")
    group.add_argument("--check", action="store_true", help="Validate all manifests; exit 1 on any failure.")
    group.add_argument("--write", action="store_true", help="Regenerate catalog.json and CATALOG.md.")
    args = parser.parse_args(argv)

    validator = load_schema()
    if args.validate:
        return cmd_validate(Path(args.validate).resolve(), validator)
    if args.check:
        return cmd_check(validator)
    if args.write:
        return cmd_write(validator)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
